# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serialUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 522)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.serial_conf_group = QtWidgets.QGroupBox(self.centralwidget)
        self.serial_conf_group.setGeometry(QtCore.QRect(10, 10, 201, 461))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.serial_conf_group.setFont(font)
        self.serial_conf_group.setObjectName("serial_conf_group")
        self.control_label = QtWidgets.QLabel(self.serial_conf_group)
        self.control_label.setGeometry(QtCore.QRect(12, 240, 61, 29))
        self.control_label.setObjectName("control_label")
        self.open_device_Btn = QtWidgets.QPushButton(self.serial_conf_group)
        self.open_device_Btn.setGeometry(QtCore.QRect(80, 240, 112, 29))
        self.open_device_Btn.setObjectName("open_device_Btn")
        self.layoutWidget = QtWidgets.QWidget(self.serial_conf_group)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 182, 203))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(13)
        self.formLayout.setObjectName("formLayout")
        self.serial_port_label = QtWidgets.QLabel(self.layoutWidget)
        self.serial_port_label.setAlignment(QtCore.Qt.AlignCenter)
        self.serial_port_label.setObjectName("serial_port_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.serial_port_label)
        self.com_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.com_comboBox.setMinimumContentsLength(0)
        self.com_comboBox.setObjectName("com_comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.com_comboBox)
        self.baud_rate_label = QtWidgets.QLabel(self.layoutWidget)
        self.baud_rate_label.setTextFormat(QtCore.Qt.PlainText)
        self.baud_rate_label.setScaledContents(False)
        self.baud_rate_label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.baud_rate_label.setWordWrap(False)
        self.baud_rate_label.setIndent(28)
        self.baud_rate_label.setOpenExternalLinks(False)
        self.baud_rate_label.setObjectName("baud_rate_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.baud_rate_label)
        self.baud_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.baud_comboBox.setEditable(False)
        self.baud_comboBox.setObjectName("baud_comboBox")
        self.baud_comboBox.addItem("")
        self.baud_comboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.baud_comboBox)
        self.data_bit_label = QtWidgets.QLabel(self.layoutWidget)
        self.data_bit_label.setScaledContents(True)
        self.data_bit_label.setObjectName("data_bit_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.data_bit_label)
        self.data_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.data_comboBox.setObjectName("data_comboBox")
        self.data_comboBox.addItem("")
        self.data_comboBox.addItem("")
        self.data_comboBox.addItem("")
        self.data_comboBox.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.data_comboBox)
        self.parity_bit_label = QtWidgets.QLabel(self.layoutWidget)
        self.parity_bit_label.setObjectName("parity_bit_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.parity_bit_label)
        self.parity_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.parity_comboBox.setObjectName("parity_comboBox")
        self.parity_comboBox.addItem("")
        self.parity_comboBox.addItem("")
        self.parity_comboBox.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.parity_comboBox)
        self.stop_bit_label = QtWidgets.QLabel(self.layoutWidget)
        self.stop_bit_label.setObjectName("stop_bit_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.stop_bit_label)
        self.stop_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.stop_comboBox.setObjectName("stop_comboBox")
        self.stop_comboBox.addItem("")
        self.stop_comboBox.addItem("")
        self.stop_comboBox.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.stop_comboBox)
        self.layoutWidget1 = QtWidgets.QWidget(self.serial_conf_group)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 290, 95, 151))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cheak_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.cheak_Btn.setObjectName("cheak_Btn")
        self.verticalLayout.addWidget(self.cheak_Btn)
        self.send_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.send_Btn.setObjectName("send_Btn")
        self.verticalLayout.addWidget(self.send_Btn)
        self.clear_send_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.clear_send_Btn.setObjectName("clear_send_Btn")
        self.verticalLayout.addWidget(self.clear_send_Btn)
        self.clear_receive_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.clear_receive_Btn.setObjectName("clear_receive_Btn")
        self.verticalLayout.addWidget(self.clear_receive_Btn)
        self.receive_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.receive_groupBox.setGeometry(QtCore.QRect(220, 10, 511, 301))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.receive_groupBox.setFont(font)
        self.receive_groupBox.setObjectName("receive_groupBox")
        self.receive_tB = QtWidgets.QTextBrowser(self.receive_groupBox)
        self.receive_tB.setGeometry(QtCore.QRect(20, 30, 471, 251))
        self.receive_tB.setObjectName("receive_tB")
        self.send_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.send_groupBox.setGeometry(QtCore.QRect(220, 340, 511, 131))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.send_groupBox.setFont(font)
        self.send_groupBox.setObjectName("send_groupBox")
        self.send_tE = QtWidgets.QTextEdit(self.send_groupBox)
        self.send_tE.setGeometry(QtCore.QRect(20, 30, 471, 81))
        self.send_tE.setObjectName("send_tE")
        self.send_label = QtWidgets.QLabel(self.centralwidget)
        self.send_label.setGeometry(QtCore.QRect(570, 325, 72, 20))
        self.send_label.setObjectName("send_label")
        self.rec_label = QtWidgets.QLabel(self.centralwidget)
        self.rec_label.setGeometry(QtCore.QRect(650, 325, 72, 20))
        self.rec_label.setObjectName("rec_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 740, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.baud_comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Serial Assistant"))
        self.serial_conf_group.setTitle(_translate("MainWindow", "串口设置"))
        self.control_label.setText(_translate("MainWindow", "  操   作"))
        self.open_device_Btn.setText(_translate("MainWindow", "打开串口"))
        self.serial_port_label.setText(_translate("MainWindow", "  串   口"))
        self.baud_rate_label.setText(_translate("MainWindow", "  波特率"))
        self.baud_comboBox.setItemText(0, _translate("MainWindow", "9600"))
        self.baud_comboBox.setItemText(1, _translate("MainWindow", "115200"))
        self.data_bit_label.setText(_translate("MainWindow", "  数据位"))
        self.data_comboBox.setItemText(0, _translate("MainWindow", "8"))
        self.data_comboBox.setItemText(1, _translate("MainWindow", "7"))
        self.data_comboBox.setItemText(2, _translate("MainWindow", "6"))
        self.data_comboBox.setItemText(3, _translate("MainWindow", "5"))
        self.parity_bit_label.setText(_translate("MainWindow", "  校验位"))
        self.parity_comboBox.setItemText(0, _translate("MainWindow", "无"))
        self.parity_comboBox.setItemText(1, _translate("MainWindow", "奇校验"))
        self.parity_comboBox.setItemText(2, _translate("MainWindow", "偶校验"))
        self.stop_bit_label.setText(_translate("MainWindow", "  停止位"))
        self.stop_comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.stop_comboBox.setItemText(1, _translate("MainWindow", "1.5"))
        self.stop_comboBox.setItemText(2, _translate("MainWindow", "2"))
        self.cheak_Btn.setText(_translate("MainWindow", "检查串口"))
        self.send_Btn.setText(_translate("MainWindow", "发送"))
        self.clear_send_Btn.setText(_translate("MainWindow", "清除发送"))
        self.clear_receive_Btn.setText(_translate("MainWindow", "清除接收"))
        self.receive_groupBox.setTitle(_translate("MainWindow", "接收区"))
        self.send_groupBox.setTitle(_translate("MainWindow", "发送区"))
        self.send_label.setText(_translate("MainWindow", "S:0"))
        self.rec_label.setText(_translate("MainWindow", "R:0"))

